common:
  name: reader
  
  image:
    name: vitaliby/appname-reader
    tag: 0.1.0
  
  serviceAccount:
    name: reader
  
  config:
    mountPath: /mnt/properties
    data:
      application.yaml: |-
        spring:
          datasource.url: jdbc:postgresql://postgresql.postgres.svc.cluster.local:5432/appdb
          datasource.username: appuser
          datasource.password: 'khPyBl7lA6Ap4JmzWOpG9S8v'
        
        management.server.port: 8081