apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
    - name: app
      protocol: TCP
      port: {{ default 80 .Values.service.application.port }}
      targetPort: {{ default 8080 .Values.service.application.targetPort }}
    - name: management
      protocol: TCP
      port: {{ default 8081 .Values.service.management.port }}
      targetPort: {{ default 8081 .Values.service.management.targetPort }}
