controller:
  persistence.size: 1Gi

provisioning:
  enabled: true
  topics:
  - name: "testCommand"
    partitions: 32
    replicationFactor: 1

listeners:
  client:
    protocol: 'PLAINTEXT'
  controller:
    protocol: 'PLAINTEXT'